export const ACTOR_PRINCIPAL_REPOSITORY = Symbol('ACTOR_PRINCIPAL_REPOSITORY');
export const LANGUAGE_REPOSITORY = Symbol('LANGUAGE_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const TOPIC_REPOSITORY = Symbol('TOPIC_REPOSITORY');
export const TAXONOMY_CHANGE_RECORD_REPOSITORY = Symbol('TAXONOMY_CHANGE_RECORD_REPOSITORY');
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');

export const FOUNDATION_REPOSITORY_TOKENS = [
  ACTOR_PRINCIPAL_REPOSITORY,
  LANGUAGE_REPOSITORY,
  CATEGORY_REPOSITORY,
  TOPIC_REPOSITORY,
  TAXONOMY_CHANGE_RECORD_REPOSITORY,
] as const;
